// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuGA7ouVBMa05El4nqC6JeowfNl54BFm4',
    appId: '1:871073062889:web:092ecafd5ca49ace33b578',
    messagingSenderId: '871073062889',
    projectId: 'markmyanswer-1b391',
    authDomain: 'markmyanswer-1b391.firebaseapp.com',
    storageBucket: 'markmyanswer-1b391.appspot.com',
    measurementId: 'G-HVTHPVEVYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAH3ozYUCJAi4ND_jLLU5ZpM2gUKNfKW4',
    appId: '1:871073062889:android:1d1b6ab0166d121433b578',
    messagingSenderId: '871073062889',
    projectId: 'markmyanswer-1b391',
    storageBucket: 'markmyanswer-1b391.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5_boWiyvbgj1UJRlLJewoUEu1FnJesJA',
    appId: '1:871073062889:ios:5da94b53516d019f33b578',
    messagingSenderId: '871073062889',
    projectId: 'markmyanswer-1b391',
    storageBucket: 'markmyanswer-1b391.appspot.com',
    iosClientId: '871073062889-ab2gcija3rvlsi0u683q13q83l9i14rf.apps.googleusercontent.com',
    iosBundleId: 'com.example.markmyanswer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5_boWiyvbgj1UJRlLJewoUEu1FnJesJA',
    appId: '1:871073062889:ios:f58cd15ef1bf3a1933b578',
    messagingSenderId: '871073062889',
    projectId: 'markmyanswer-1b391',
    storageBucket: 'markmyanswer-1b391.appspot.com',
    iosClientId: '871073062889-l3dpdljhpg8eltg4sbqpttk2pd9j3k1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.markmyanswer.RunnerTests',
  );
}
